version: "3.5"
services:
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: sd.consumer
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: messages
  app:
    build: .
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_NAME: messages
      MONGO_USER: sd.consumer
      MONGO_PASS: 123
      RABBITMQ_URL: amqp://rabbitmq
    ports:
      - 3030:3030
    volumes: 
      - .:/usr/app
    links:
      - mongo
    depends_on:
      - mongo